Urso.SlotBase.Modules.StatesManager.Actions = {
    BaseTransportAction: require('./baseTransportAction'),
    TransportInitAction: require('./transportInitAction'),
    ServerSpinRequestAction: require('./serverSpinRequestAction'),
    ServerBalanceRequestAction: require('./serverBalanceRequestAction'),
    WaitingForInteractionAction: require('./waitingForInteractionAction'),
    UpdateServerSettingsAction: require('./updateServerSettingsAction'),
    ServerApiVersionRequestAction: require('./serverApiVersionRequestAction'),
    ServerCheckBrokenGameRequestAction: require('./serverCheckBrokenGameRequestAction'),
    ServerAuthRequestAction: require('./serverAuthRequestAction'),
    LoadDefaultSceneAction: require('./loadDefaultSceneAction'),
    InitUiLogicAction: require('./initUiLogicAction'),
    UpdateBalanceAction: require('./updateBalanceAction'),
    MakeBetAction: require('./makeBetAction'),
    UpdateWinTextAction: require('./updateWinTextAction'),
    ResetWinTextAction: require('./resetWinTextAction'),
};
